dist: trusty
language: node_js
node_js:
  - "8"

branches:
  only:
    - master
    - beta
    - /^greenkeeper/.*$/

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash

install:
  - yarn global add @angular/cli
  - yarn global add typings
  - yarn global add firebase-tools
  - yarn install

script:
  - yarn lint
  - yarn prod

deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_TOKEN
